### ISSUE TITLE
vnStatd has missing attribute `vnstatd_var_lib_t` and `domain_can_mmap_files`

### ISSUE THREAD

**Issue by theKAKAN** [fedora-selinux/selinux-policy#711] opened 2021-05-03 15:45 UTC
Hello, I just installed vnstat using `sudo dnf install vnstat` and after trying to start it using `sudo systemctl start vnstat`, I constantly ran into issues, and it stopped abruptly.  
After poking around for some time, it seems like the issue is with SELinux policy not allowing read access on the database file(s).
Here's the log that I had:
```
May 03 01:28:26 [REDACTED] setroubleshoot[19529]: SELinux is preventing vnstatd from getattr access on the file /var/lib/vnstat/vnstat.db.
                                             
                                             *****  Plugin restorecon (94.8 confidence) suggests   ************************
                                             
                                             If you want to fix the label. 
                                             /var/lib/vnstat/vnstat.db default label should be vnstatd_var_lib_t.
                                             Then you can run restorecon. The access attempt may have been stopped due to insufficient permissions to access a parent di>
                                             Do
                                             # /sbin/restorecon -v /var/lib/vnstat/vnstat.db
                                             
                                             *****  Plugin catchall_labels (5.21 confidence) suggests   *******************
                                             
                                             If you want to allow vnstatd to have getattr access on the vnstat.db file
                                             Then you need to change the label on /var/lib/vnstat/vnstat.db
                                             Do
                                             # semanage fcontext -a -t FILE_TYPE '/var/lib/vnstat/vnstat.db'
                                             where FILE_TYPE is one of the following: NetworkManager_log_t, NetworkManager_tmp_t, abrt_helper_exec_t, abrt_tmp_t, abrt_u>
                                             Then execute:
                                             restorecon -v '/var/lib/vnstat/vnstat.db'
                                             
                                             
                                             *****  Plugin catchall (1.44 confidence) suggests   **************************
                                             
                                             If you believe that vnstatd should be allowed getattr access on the vnstat.db file by default.
                                             Then you should report this as a bug.
                                             You can generate a local policy module to allow this access.
                                             Do
                                             allow this access for now by executing:
                                             # ausearch -c 'vnstatd' --raw | audit2allow -M my-vnstatd
                                             # semodule -X 300 -i my-vnstatd.pp
                                             
May 03 01:28:26 [REDACTED] setroubleshoot[19529]: SELinux is preventing vnstatd from getattr access on the file /var/lib/vnstat/vnstat.db. For complete SELinux messages run:>
```

After running:
```
semanage fcontext -a -t vnstatd_var_lib_t '/var/lib/vnstat/vnstat.db'
/sbin/restorecon -v /var/lib/vnstat/vnstat.db
```
I ran into issues with the DB's mmap access( _which sounds more of a F34 issue than vnstat one tbh_ )
```
May 03 01:31:47 [REDACTED] setroubleshoot[19734]: SELinux is preventing vnstatd from map access on the file /var/lib/vnstat/vnstat.db-shm.
                                             
                                             *****  Plugin catchall_boolean (89.3 confidence) suggests   ******************
                                             
                                             If you want to allow domain to can mmap files
                                             Then you must tell SELinux about this by enabling the 'domain_can_mmap_files' boolean.
                                             
                                             Do
                                             setsebool -P domain_can_mmap_files 1
                                             
                                             *****  Plugin catchall (11.6 confidence) suggests   **************************
                                             
                                             If you believe that vnstatd should be allowed map access on the vnstat.db-shm file by default.
                                             Then you should report this as a bug.
                                             You can generate a local policy module to allow this access.
                                             Do
                                             allow this access for now by executing:
                                             # ausearch -c 'vnstatd' --raw | audit2allow -M my-vnstatd
                                             # semodule -X 300 -i my-vnstatd.pp
```

So, running:
```
setsebool -P domain_can_mmap_files 1
```
did fix it for me.

Thank you for this wonderful tool, and do say if you need any other information

In case it helps, I'm running stock Fedora 34 and here's some more information
```
$ uname -a
Linux [REDACTED] 5.11.16-300.fc34.x86_64 #1 SMP Wed Apr 21 13:18:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
vnStat version:
```
$ dnf info vnstat
Last metadata expiration check: 1:06:28 ago on Monday 03 May 2021 12:41:17 AM.
Installed Packages
Name         : vnstat
Version      : 2.6
Release      : 4.fc34
Architecture : x86_64
Size         : 352 k
Source       : vnstat-2.6-4.fc34.src.rpm
Repository   : @System
From repo    : fedora
Summary      : Console-based network traffic monitor
URL          : http://humdi.net/vnstat/
License      : GPLv2
Description  : vnStat is a console-based network traffic monitor that keeps a
             : log of daily network traffic for the selected interface(s).
             : vnStat isn't a packet sniffer. The traffic information is
             : analyzed from the /proc file-system, so vnStat can be used
             : without root permissions. See the web-page for few 'screenshots'.
```

**Comment by zpytela** [comment] 2021-05-03 17:44
@theKAKAN I cannot reproduce this issue: After installation, the directory has correct type and the database inherits the parent directory type:
```
  # ls -Zal /var/lib/vnstat/
total 76
drwxr-xr-x.  2 vnstat vnstat system_u:object_r:vnstatd_var_lib_t:s0  4096 May  3 13:41 .
drwxr-xr-x. 29 root   root   system_u:object_r:var_lib_t:s0          4096 May  3 13:40 ..
-rw-r--r--.  1 vnstat vnstat system_u:object_r:vnstatd_var_lib_t:s0 69632 May  3 13:41 vnstat.db
```

Resorecon indeed fixes this issue, but I cannot tell why you ran into this issue. You can remove the custom semanage-fcontext rule and check:
```
  # matchpathcon /var/lib/vnstat /var/lib/vnstat/vnstat.db
/var/lib/vnstat system_u:object_r:vnstatd_var_lib_t:s0
/var/lib/vnstat/vnstat.db       system_u:object_r:vnstatd_var_lib_t:s0
```

**Comment by zpytela** [comment] 2021-05-03 17:46
For the other issue, details are missing, but I suppose the fact vnstatd has almost all but map permission:
```
  # sesearch -A -s vnstatd_t -t vnstatd_var_lib_t -c file
allow domain file_type:file map; [ domain_can_mmap_files ]:True
allow vnstatd_t vnstatd_var_lib_t:file { append create getattr ioctl link lock open read rename setattr unlink watch watch_reads write };
```
means this permission needs to be added to the policy.

**Comment by theKAKAN** [comment] 2021-05-11 06:03
Sorry for the late reply. Indeed, I can't seem to recreate the first issue either. So, it seems like it was something to do with my system...

The second issue, it seems, happens after I uninstalled some packages, which might have removed the mmap permission globally.  
I'm still not sure which, but for now, I suppose this could be considered an issue as the vnstat policy doesn't explicitly ask for the mmap permission...

**Comment by zpytela** [comment] 2021-05-11 06:54
Setting the `domain_can_mmap_files` boolean to on adds the map permission to all domains. You can list all customizations with:

```
semanage export
```

**Comment by zpytela** [comment] 2021-05-11 12:54
Closing in favor of https://github.com/fedora-selinux/selinux-policy/pull/733

**Closed as completed by zpytela** 2021-05-11 12:54 UTC
