### ISSUE TITLE
Add selinux policy for cloud-init-hotplug

### ISSUE THREAD

**Issue by yangzz-97** [fedora-selinux/selinux-policy#1108] opened 2022-03-14 12:03 UTC
Cloud-init introduces cloud-init-hotplug.socket requires systemd have add_name capability in the directory /run/cloud-init/hook-hotplug-cmd, I think we need to add a security policy for cloud init hotplug

https://bugs.launchpad.net/cloud-init/+bug/1936229

**Comment by yangzz-97** [comment] 2022-03-29 13:22
@zpytela Could you help me? Thank you

**Comment by zpytela** [comment] 2022-05-06 15:46
@yangzz-97 I am sorry for the delay in answering. Support for cloud-init was enhanced in selinux-policy in the past months, anyway I cannot reproduce the problem now. Please let me know if it works for you too.

**Comment by zpytela** [comment] 2022-12-08 18:34
This problem is not reproducible any longer, so closing the issue. Feel free to reopen it if you can.

**Closed as completed by zpytela** 2022-12-08 18:34 UTC
